### ISSUE TITLE
Move from stylis to a pre-processor with more appropriate compile time features

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#100]
We don't need the library to small since it's done at comiled time.

## Stylus

Huge benefits, namely built in functions for free.

https://stylus-lang.com/docs/bifs.html

## PostCSS

Kind of a standard. Loads of plugins.

**Comment by theKashey** [comment]
I vote for PostCSS.

**Comment by jjcm** [comment]
I vote you remove @theKashey from this project. Stylus is way cooler and I made you a logo

**Comment by theKashey** [comment]
Hey! Michael started this first!

**Comment by madou** [comment]
ehehhehe

**Comment by theKashey** [comment]
It has plugins, as you said. Standard tooling even outside of js. Well, @ai is also a benefit.
Plus upcoming [PostCSS 8](https://evilmartians.com/chronicles/postcss-8-is-coming-here-is-what-it-brings) introduces a visitor pattern for transformations, so it would be a joy to use it.
I am really not sure about `stylus`, but PostCSS is very properly maintained.
