### ISSUE TITLE
Change Style import to import directly from @compiled/style

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#103]
It means for people who can't rely on treeshaking they still get the smallest bundle size. We can also potentially be in trouble for name clashes, so throw an underscore in there for good measure.

Before

```
import { Style } from '@compiled/css-in-js';
```

After

```
import _Styl from '@compiled/style';
```

**Comment by flexdinesh** [comment]
@madou this would mean 

```
import React from 'react';
import { Style } from '@compiled/css-in-js';
export const ColoredText = React.forwardRef(
  ({ as: C = 'span', ...props }, ref) => (
    <>
      <Style hash="css-zd46j1">{['.css-zd46j1{color:#ff5630;}']}</Style>
      <C
        {...props}
        ref={ref}
        className={
          'css-zd46j1' + (props.className ? ' ' + props.className : '')
        }
      />
    </>
  )
);
```

will now become 

```
import React from 'react';
import _Styl from '@compiled/style';
export const ColoredText = React.forwardRef(
  ({ as: C = 'span', ...props }, ref) => (
    <>
      <_Styl hash="css-zd46j1">{['.css-zd46j1{color:#ff5630;}']}</_Styl>
      <C
        {...props}
        ref={ref}
        className={
          'css-zd46j1' + (props.className ? ' ' + props.className : '')
        }
      />
    </>
  )
);
```

Instead of opting for underscrore, what do you think about making it as a plugin option, so consumers can choose a different name if and when there's a name collision?

**Comment by madou** [comment]
yeah exactly dinesh. i think we could introduce a option but it should just work out of the box IMO with something very unlikely to colide.

**Comment by gwyneplaine** [comment]
@madou  keen to pick this up to familiarize myself with the repo.  I'm assuming this applies to the CC export as well? 

*Before*
```type=js
  import React from \\"react\\";
  import { CC, Style } from '@compiled/css-in-js';
  const StyledDiv = /*#__PURE__*/React.forwardRef(({
      as: C = \\"div\\",
      ...props
    }, ref) => <CC><Style hash=\\"1x3e11p\\">{[\\".cc-1x3e11p{font-size:12px}\\"]}</Style><C {...props} ref={ref} className={\\"cc-1x3e11p\\" + (props.className ? \\" \\" + props.className : \\"\\")} /></CC>);
```

*After*
```type=js
  import React from \\"react\\";
  import _Style, { CC } from '@compiled/style';
  const StyledDiv = /*#__PURE__*/React.forwardRef(({
      as: C = \\"div\\",
      ...props
    }, ref) => <CC><_Style hash=\\"1x3e11p\\">{[\\".cc-1x3e11p{font-size:12px}\\"]}</Style><C {...props} ref={ref} className={\\"cc-1x3e11p\\" + (props.className ? \\" \\" + props.className : \\"\\")} /></CC>);
```

**Comment by madou** [comment]
O DAM HES JUMPIN IN cc @danieldelcore look at him go

yeah exactly! this will be a good issue to work on to familiarize you with typescript transformers too.

one nuance will be needing to ensure `@compiled/css-in-js` import gets removed - which means every api transformer needs to check "am i the last compiled import" and then when they remove themselves - they also remove the entire import declaration

you can see the current logic inside  `packages/ts-transform/src/utils/visit-source-file-ensure-style-import.tsx`

**Comment by madou** [comment]
FYI this will affect you https://github.com/atlassian-labs/compiled-css-in-js/pull/187
