### ISSUE TITLE
Resolve browserlist from file or package json

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#104]
See: https://github.com/postcss/autoprefixer#using-environment-variables-to-support-css-grid-prefixes-in-create-react-app

```
"browserslist": {
  "production": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ],
  "development": [
    "last 1 chrome version",
    "last 1 firefox version",
    "last 1 safari version",
    "last 1 ie version"
  ]
}
```

Would be dope to pick this up automatically and then set the CSS compiler with it.

**Comment by madou** [comment]
unblocked via #175

**Comment by ankeetmaini** [comment]
I think if the `overrideBrowserslist` option is removed `autoprefixer` will honour `browserslist` config/env vars automatically then.

```diff
const result = postcss([
    parentOrphenedPseudos(),
    nested(),
-    autoprefixer({
-      overrideBrowserslist: ['IE 11', '> 0.5%', 'last 2 versions', 'Firefox ESR', 'not dead'],
-    }),
+    autoprefixer()
    ...(opts.minify ? minify() : [whitespace]),
    extractStyleSheets({ callback: (sheet: string) => sheets.push(sheet) }),
  ]).process(cssWithSelector, {
    from: undefined,
  });
```

**Comment by madou** [comment]
hey thanks - cool!

and I guess it just defaults to auto prefixers default?

**Comment by ankeetmaini** [comment]
yes!

**Comment by madou** [comment]
Siiiick easy fix - want to delete some lines of code and add a new feature?
;-)

**Comment by madou** [comment]
Oh you did! Noice
