### ISSUE TITLE
Generated hash could collide with emotion hash

### ISSUE THREAD

**Issue by flexdinesh** [atlassian-labs/compiled-css-in-js#131]
The hash generated by compiledcss can collide with the hash generated by emotion. It's a good idea to change it.

How it looks now?
```.css-xxxxxx {}```

How it could look?
```.ccss-xxxxxx {}```

**Comment by madou** [comment]
I reckon `cc` for compiled components

**Comment by madou** [comment]
tiny PR could fix this in `packages/ts-transform/constants.tsx`
