### ISSUE TITLE
Inline identifiers that are constants into CSS

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#167]
Right now we end up making any identifiers into a dynamic variable. We can optimize this by inlining identifiers that are constants instead.

Before

```
const color = 'blue';

<div
  css={{ color: blue }}
>

<div style={{ '--var-abc123': color }}>
.cc-abc123 { color: var(--var-abc123); }
```

After

```
<div
  css={{ color: blue }}
>

<div>
.cc-abc123 { color: blue; }
```

**Comment by ankeetmaini** [comment]
I'd like to take a shot at this!

**Comment by madou** [comment]
cool let me know if you need any help getting started 😄
