### ISSUE TITLE
Interpolation in styled template literal doesn't support values or expressions

### ISSUE THREAD

**Issue by jaredcrowe** [atlassian-labs/compiled-css-in-js#197]
**Describe the bug**
When using the styled component API, expression interpolation only seems to work when using inline functions or a variable that points to a value.

**To Reproduce**
The following compiles successfully but produces broken CSS:

```
const Div = styled.div`
  border-radius: ${2 + 2}px;
`;
```

```
const br = 2 + 2;
const Div = styled.div`
  border-radius: ${br}px;
`;
```

The following fails to compile:

```
const Div = styled.div`
  border-radius: ${4}px;
`;
```

```
const Div = styled.div`
  border-radius: ${'4'}px;
`;
```

```
const Div = styled.div`
  border-radius: ${`${4}`}px;
`;
```

```
const getBr = () => 4;
const Div = styled.div`
  border-radius: ${getBr}px;
`;
```

These work correctly, however:

```
const br = 4;
const Div = styled.div`
  border-radius: ${br}px;
`;
```

```
const Div = styled.div`
  border-radius: ${() => 2 + 2}px;
`;
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 0.3.2

**Comment by madou** [comment]
Thanks mate!

Can you double check if this works?

```
const br = 2 + 2;
const Div = styled.div`
  line-height: ${br};
`;
```

I'll also release the latest version of Compiled just to make sure.

**Comment by jaredcrowe** [comment]
That doesn't work in v0.3.2 either. It compiles but breaks the styles.

Just tried upgrading to v0.4 and I get an `Element type is invalid` runtime error in the component even when not using interpolation 😬

**Comment by madou** [comment]
I'll look into it 👍

**Comment by madou** [comment]
I have a PR up here https://github.com/atlassian-labs/compiled-css-in-js/pull/198 to fix it 👍
