### ISSUE TITLE
Post phase one rough ideas

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#2]
If we've gotten this to a state where its faster, better, and we have decided we want to go ahead with consuming this in Atlaskit we'll then progress to these.

## Phase 2 - feature completeness

- [ ] improve developer experience/enrich error messages/constraints
- [ ] investigate theming API
- [x] add babel plugin support
- [ ] keyframes #14 
- [ ] mixins #17 
- [ ] theming #18
- [ ] runtime evaluated variables #28 

## Phase 3 - UNLIMITED POWER

- [ ] new transformer to extract compiled css to a file(s) vs. #36 
- [ ] new transformer that can run over all of your compiled css to "atomic-ify" it
- [x] see if we need a small runtime to move `style` tags to the document head

**Comment by marionebl** [comment]
What is your stance on creating an optional “production” (static?) mode that extracts all generated css into a separate file?

**Comment by madou** [comment]
not against it - it could be done pretty easily i think

**Comment by madou** [comment]
This is all referenced in other issues now, closing.
