### ISSUE TITLE
Replace post css selector parsing with the official library

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#200]
Right now we're parsing it with a `string.split` - we should move over to the official parsing library instead: https://github.com/postcss/postcss-selector-parser

Code to change: https://github.com/atlassian-labs/compiled-css-in-js/blob/master/packages/ts-transform/src/utils/css-transform.tsx#L30

Now what we have works - so there's no real pressing need to change it. But this is a good first issue I think 😄.

---

That said looking at some of the issues on there are interesting (like: https://github.com/postcss/postcss-selector-parser/issues/204) - but we probably have the same issue ATM tbh.

**Comment by pgmanutd** [comment]
Good first issue 😋😋Should I start with this 😉 😉

**Comment by madou** [comment]
Hi! Yeah sure 😄 Give it a go.
