### ISSUE TITLE
Using the css prop with a value that is a template literal fails to compile

### ISSUE THREAD

**Issue by jaredcrowe** [atlassian-labs/compiled-css-in-js#205]
**Describe the bug**
This fails:

```javascript
const gridSize = 4;
const Div = () => <div css={{
  padding: `0 ${gridSize}px`,
}} />;
```

This works, however:

```javascript
const gridSize = 4;
const padding = `0 ${gridSize}px`;
const Div = () => <div css={{
  padding,
}} />;
```

**Comment by madou** [comment]
thanks!

**Comment by madou** [comment]
hey just tested this out locally - this works for me - what do you see?

![image](https://user-images.githubusercontent.com/6801309/82994481-93bc4c00-a045-11ea-8248-0ee2a1ec451a.png)

**Comment by jaredcrowe** [comment]
Ah sorry, maybe my reduced case was too simple. Try it in a block with another rule after it. It looks like it's not appending the semicolon. Here's my real-world use case:

<img width="664" alt="Screen Shot 2020-05-27 at 7 24 09 pm" src="https://user-images.githubusercontent.com/4995433/83001886-ae93be00-a04f-11ea-8701-eee7529b0e67.png">

And here's the error I get:

<img width="378" alt="Screen Shot 2020-05-27 at 7 24 42 pm" src="https://user-images.githubusercontent.com/4995433/83001922-bc494380-a04f-11ea-81ab-0ee84654a5cb.png">

**Comment by madou** [comment]
Cheers will fix 🙏

**Comment by madou** [comment]
Fix for it here https://github.com/atlassian-labs/compiled-css-in-js/pull/206

Turns out when moving from Stylis to PostCSS it's a bit more stricter about semi-colons - which TBH is a good thing. 

Also you should join the Atlassian Orgs on Github! http://go/opensource
