### ISSUE TITLE
Please name this library something else

### ISSUE THREAD

**Issue by TalMat** [atlassian-labs/compiled-css-in-js#226]
Searching the web for support here is going to be as difficult as finding parts for a car named "Engine"

I believe actually naming the library is a good solution. You could randomly pick five letters. You could pick almost any word that is not a programming technical term. You could even just name it with an emoji. Any of this would be more effective.

**Comment by madou** [comment]
Thanks! We will be considering name changes soon. When it moves out of
Atlassian labs it should have one.

Cheers,
Michael
