### ISSUE TITLE
RFC: CSS extraction bundler plugin

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#36]
Compiles (it would be createElement though instead of jsx)

```tsx
// component.tsx
<>
  <style>.a { font-size: 10px; }</style>
  <div class="a">...</div>
</>
```

To

```tsx
// component.tsx
import './component.css';
<div class="a">...</div>
```

```css
// component.css
.a { font-size: 10px; }
```

- Css extraction and the like can be left in user land.
- Need to be a bundler plugin (Webpack & Parcel)

**Comment by theKashey** [comment]
> How do we solve critical CSS with SSR?

🤔: What about https://github.com/theKashey/used-styles?

**Comment by madou** [comment]
> > How do we solve critical CSS with SSR?
> 
> 🤔: What about https://github.com/theKashey/used-styles?

hey cool library - can investigate later when we get into the details about this one :D

**Comment by avindra** [comment]
Webpack and rollup are supported in linaria. An investigation into [more aggressive output](https://github.com/callstack/linaria/issues/532) has already begun. Recommend having a look, as the linaria folks have covered a lot of similar ground (there is also a styled api)

**Comment by madou** [comment]
Thanks - this probably won't be touched for a bit but it's definitely on our radar to work on 😄 

Any thoughts in the area while you're here?

**Comment by madou** [comment]
Merging into #58
