### ISSUE TITLE
Support "as" prop on styled components

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled-css-in-js#39]
https://www.styled-components.com/docs/api#as-polymorphic-prop

**Comment by marionebl** [comment]
What solution sketch do you have in mind for this? My first hunch is we would have to move the component up to where we currently create a fragment. Does that break other assumptions?

```ts
styled.div`color: blue;`;
```
→
```ts
// pseudo code
props => (
  <(props.as || "div")>
    <style>{'.a { color: blue; }'}</style>
    {props.children}
  </(props.as || "div")>
);
```

**Comment by madou** [comment]
hey! yeah it kind of would tbh! ideally we keep most of the transformations similar

i'd expect something like this:

```
styled.div`
  color: blue;
`;
```

```
<>
  <style>{'.a { color: blue; }'}</style>
  <(props.as || "div") className="a">hello, world!</(props.as || "div")>
</>
```

**Comment by madou** [comment]
Added in https://github.com/atlassian-labs/compiled-css-in-js/commit/940d6a847ccf9e2e0b7820ab0c898f390e86aae1
