### ISSUE TITLE
RFC: Trousers API

### ISSUE THREAD

**Issue by theKashey** [atlassian-labs/compiled-css-in-js#53]
I'm pretty sure https://github.com/danieldelcore/trousers has the best API among all other `css-in-js` interfaces.

Any plans to use something as cool as it, rather that something not cool (...as usual)

cc @danieldelcore

**Comment by madou** [comment]
no plans atm. other than effort i don't think theres anything stopping us supporting other apis

right now the plan is to have a similar api to emotion/styled to ease migration

**Comment by madou** [comment]
Speak about this here: https://github.com/atlassian-labs/compiled-css-in-js/issues/137
